# Generated by Django 5.2.11 on 2026-03-31 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_taskrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='source_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_task', to='tasks.taskrequest'),
        ),
    ]
